### ISSUE TITLE
Installation failed on Win10 "No such file or directory"

### ISSUE THREAD

**Issue by avicodec** [noise-lab/iot-inspector-client#11]
At the end of the installation (Ubuntu on Win10, dependencies ok), linux-setup.sh writes:
"Cloning into 'iot-inspector-client'...
fatal: unknown error occurred while reading the configuration files
linux-setup.sh: line 15: cd: /home/avicodec/princeton-iot-inspector/iot-inspector-client/v2-src: No such file or directory
bash: ./linux-install-dependencies.sh: No such file or directory"

=> Cloning has failed due to an error with configuration file ? (I'm not a specialist)

**Comment by crazyideas21** [comment]
We never tested IoT Inspector on the Ubuntu subsystem of Windows 10. Our guess is that the setup script installed IoT Inspector to `/root` instead, which might have caused the error above.

Can you try the following?

1. On the command line, run `sudo su`, i.e., you'd be running as root.
2. Run `linux-setup.sh`.
3. Once setup is complete, run IoT Inspector by following the instructions --- while remaining as root.

Let us know if these instructions above fix the issue.

**Comment by avicodec** [comment]
Hello, no it does not change anything, I have the same error are running the script. I thin about a configuration issue in my Win10 Ubuntu installation which prevent git to work properly.

I will wait for the Windows version :-)
