### ISSUE TITLE
WARNING: Do not use the development server in a production environment.

### ISSUE THREAD

**Issue by AnthonyMastrean** [noise-lab/iot-inspector-client#15]
Looks like a Flask warning... 

```
 * Serving Flask app "webserver" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.   Use a production WSGI server instead.
 * Debug mode: off
```

The [Flask docs](http://flask.pocoo.org/docs/1.0/deploying/) mention

> While lightweight and easy to use, Flask’s built-in server is not suitable for production as it doesn’t scale well. Some of the options available for properly running Flask in production are documented here.

If it's OK to consider this a "dev" app and run on the Flask server (and not have to figure out some other webserver option), looks like there's some kind of .env file or ENV vars that might sort things out.

https://stackoverflow.com/questions/50284753/warning-message-while-running-flask

**Comment by crazyideas21** [comment]
That's fine because the Flask instance is bound to `127.0.0.1` only with the correct CORS restrictions.
