### ISSUE TITLE
iot-inspector-client fails to start 

### ISSUE THREAD

**Issue by rajeevsingh-ag** [noise-lab/iot-inspector-client#2]
iot-inspector-client fails to start after providing admin access. 

Environment: 
+ macOS Mojave 10.14.4 
+ MacBook Pro 15-inch 2017, intel Core i7, 16 GB RAM, 1 TB SSD

1. Followed instructions and launched start-inspector utility 
2. Got prompted to provide admin privileges 
3. After typing in password, utility disappears and the web-page does not refresh

I have a suspicion that because I have another ARP-spoofing device on the network https://meetcircle.com/ , that is causing iot-inspector-client to not work. Please confirm.

**Comment by crazyideas21** [comment]
We haven't tested with another ARP spoofing device. Our suspicion is that you may have a VPN or Docker that confused `scapy`. See this issue: https://github.com/noise-lab/iot-inspector-client/issues/3

Feel free to send us your log file so that we can take a look in detail. Thanks!
