### ISSUE TITLE
Got 404 when try to download  start_inspector_mac.zip 

### ISSUE THREAD

**Issue by olhaviko** [noise-lab/iot-inspector-client#34]

**Comment by crazyideas21** [comment]
@kumarde Could you check latest macOS Catalina build into [github's Release](https://help.github.com/en/github/administering-a-repository/creating-releases)? 

Originally the binary was checked [into the git repo](https://iot-inspector.princeton.edu/blog/post/getting-started/#i-class-fab-fa-apple-i-macos) and [the download page](https://iot-inspector.princeton.edu/blog/post/getting-started/#i-class-fab-fa-apple-i-macos) points to this location.

**Comment by crazyideas21** [comment]
Pushed a temporary fix. Now the download page links to the old binary from a previous commit: https://iot-inspector.princeton.edu/blog/post/getting-started/

**Comment by olhaviko** [comment]
Now I can download the start_inspector_mac.zip, but still can't run the app.
A near week ago I used inspector normally without any issues. 
I created new issue for this: https://github.com/noise-lab/iot-inspector-client/issues/35

**Comment by prakxys** [comment]
getting 400 after this was fixed

**Comment by crazyideas21** [comment]
> getting 400 after this was fixed

You got `400` after visiting which URL? I can't replicate your error.

**Comment by crazyideas21** [comment]
I can't replicate the problem and will close the issue. Feel free to reopen the issue if you can provide a detailed description of your problem.
