### ISSUE TITLE
Can't start the inspector

### ISSUE THREAD

**Issue by olhaviko** [noise-lab/iot-inspector-client#35]
I can't start the inspector, although it worked fine near the week ago.
macOS High Sierra 10.13.6 

Steps to reproduce:
1. Go to https://iot-inspector.princeton.edu/blog/post/getting-started/#i-class-fab-fa-apple-i-macos
2. Download start_inspector_mac.zip and unzip
3. Open start_inspector.app 
Result:
- popup "IoT Inspector" with the message "Starting IoT Inspector..." appears
- https://inspector.cs.princeton.edu/setup?started_from_app=yes page opened in Chrome browser
 - enter administrative password popup appears (with the title "start_inspector wants to make changes")
4. Enter the administrative password and click "ok"
Result:
- start_inspector.app is terminated
- "Starting IoT Inspector" page in the browser is not refreshed even if wait 30 s, always loading
5. Open https://inspector.cs.princeton.edu/ in a separate Firefox or Google Chrome window
Result:
- "Setting up IoT Inspector" page opened in the browser and it proposes to download IoT Inspector and simply run it. If trying to do this -  steps 2-5 will be reproduced again.

NOTE:  When running start_inspector.app first time, it creates a princeton-iot-inspector folder in home directory. There are 3 files: 
- update_inspector.sh
- start_inspector_mac.pending
- start_inspector_mac
When I run start_inspector_mac in console the output:
`/Users/olha/princeton-iot-inspector/start_inspector_mac ; exit;
/Users/olha/princeton-iot-inspector/start_inspector_mac: line 1: 404:: command not found
logout
`

**Comment by bverkron** [comment]
I have the same issue.

**Comment by kacomess** [comment]
I've experienced precisely the same problem on Apple OS 10.15.1

**Comment by bverkron** [comment]
I tried to step through the script by manually running each line.  This was as far as I got. Tried a few previous commits too but they all fail with the same error. I would imagine that whatever was needed would be installed by the script but I suppose one could try manually installing the missing module. Don't have time to dig any deeper right now.

```
$ python3 start_inspector.py
Traceback (most recent call last):
  File "start_inspector.py", line 2, in <module>
    import inspector
  File "/Users/ben/Downloads/iot-inspector-client-91c0c24cf88192fe7a5dd57cb7591d488f54a7f7/v2-src/inspector.py", line 5, in <module>
    import utils
  File "/Users/ben/Downloads/iot-inspector-client-91c0c24cf88192fe7a5dd57cb7591d488f54a7f7/v2-src/utils.py", line 8, in <module>
    import scapy.all as sc
ModuleNotFoundError: No module named 'scapy'
```

**Comment by crazyideas21** [comment]
Let me test this.

**Comment by crazyideas21** [comment]
Issue should be fixed; see https://github.com/noise-lab/iot-inspector-client/commit/decfac1535b3b471249db88ca6a48bb6ee3f7b9c for details. Please reopen this issue if you see further problems. Sorry for this bug.
