### ISSUE TITLE
error: bad magic number in net disco

### ISSUE THREAD

**Issue by ggmartins** [noise-lab/iot-inspector-client#39]
Hey there folks, I've got this error after running iot inpector for the second time today (I see that the latest code was updated/pulled from git right after I ctrl-c. This is in a raspberry pi 4. Also, I had to manually install netifaces using pip3 to make it (almost) work. 
```
Traceback (most recent call last):
  File "start_inspector.py", line 2, in <module>
    import inspector
  File "/root/princeton-iot-inspector/iot-inspector-client/v2-src/inspector.py", line 12, in <module>
    from netdisco_wrapper import NetdiscoWrapper
  File "/root/princeton-iot-inspector/iot-inspector-client/v2-src/netdisco_wrapper.py", line 13, in <module>
    from netdisco.discovery import NetworkDiscovery
ImportError: bad magic number in 'netdisco': b'\x03\xf3\r\n'
```

**Comment by crazyideas21** [comment]
Can you clone the latest code into a brand new directory and try again? This problem could be related to stale `pyc` files, especially given we recently bumped the python version from 2 to 3.

See:
- https://github.com/Miserlou/Zappa/issues/854
- https://stackoverflow.com/questions/52698854/importerror-bad-magic-number-in-dateparser-b-x03-xf3-r-n

**Comment by ggmartins** [comment]
looks like a different problem now (after cloning the entire repo again):

```
./linux-start-inspector.sh 
Starting IoT Inspector...
Traceback (most recent call last):
  File "start_inspector.py", line 2, in <module>
    import inspector
  File "/root/princeton-iot-inspector/iot-inspector-client/v2-src/inspector.py", line 5, in <module>
    import utils
  File "/root/princeton-iot-inspector/iot-inspector-client/v2-src/utils.py", line 21, in <module>
    from scapy.arch.windows import NetworkInterface
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/windows/__init__.py", line 21, in <module>
    from scapy.arch.windows.structures import _windows_title, \
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/windows/structures.py", line 15, in <module>
    import ctypes.wintypes
  File "/usr/lib/python3.7/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported
Updating software...
Already up to date.
```

**Comment by ggmartins** [comment]
FYI
```
commit cb84ec48ca3b36f736887f7e3861750d3a4ac3b0 (HEAD -> master, origin/master, origin/HEAD)
Author: Danny Y. Huang <crazyideas21@gmail.com>
Date:   Tue Dec 17 15:07:09 2019 -0500

    Update README.md
    
    Added description on Windows 10 support.

commit 393bf81b159bbc0c7a13c2262cd5387938de4ab0
Merge: 17bd533 6a56351
Author: Danny Y. Huang <crazyideas21@gmail.com>
Date:   Tue Dec 17 15:06:08 2019 -0500

    Merge pull request #40 from noise-lab/kumarde/add_windows_support
    
    Add windows support. Independently tested by @kumarde and @crazyideas21 on their Windows 10 installations. In the case of @crazyideas21, his Windows 10 runs on a bare metal Lenovo laptop.

```

**Comment by kumarde** [comment]
@ggmartins good catch, thanks! I will update this – I know the fix.

**Comment by kumarde** [comment]
@ggmartins mind giving the latest master a try? Fixed here: https://github.com/noise-lab/iot-inspector-client/pull/46

**Comment by ggmartins** [comment]
it works now after installing tcpdump. Thanks!

**Comment by crazyideas21** [comment]
> it works now after installing tcpdump

@ggmartins What do you mean by "after installing tcpdump"? Did you have to install additional software?

**Comment by ggmartins** [comment]
yes, some library, possibly scapy was complaining about missing tcpdump and dumping a stack trace every second. I can purge tcpdump and see if I can get the exact output for that if that helps.

**Comment by crazyideas21** [comment]
> I can purge tcpdump and see if I can get the exact output for that if that helps.

@ggmartins That'd be great. Thanks! The users are not expected to install any missing packets; the installation process should be as easy as possible.
