### ISSUE TITLE
Internet of Things (IoT)/Google Home / google_cast / b11a84b8-b4e5-7c91-9607-7fd338f7db1e.local. / Chromecast / /setup/icon.png / TonCast TV

### ISSUE THREAD

**Issue by Toontje** [noise-lab/iot-inspector-client#7]
The /setup/icon.png , should that be an icon?

**Comment by crazyideas21** [comment]
`/setup/icon.png` is a part of the SSDP message announced by your Chromecast. It should live on your Chromecast's local HTTP server.
