### ISSUE TITLE
IoTinspector.org offline

### ISSUE THREAD

**Issue by malexmave** [noise-lab/iot-inspector-client#84]
https://iotinspector.org/ no longer loads for me, or rather: only shows an empty page with the HTML content:

```html
<html>
  <head>
    <meta property="og:url" content="https://iot-inspector.lpages.co/iotinspectororg/" />
    <link rel="opengraph" href="https://iot-inspector.lpages.co/iotinspectororg/" />
    <script src="//iot-inspector.lpages.co/_/js/iotinspectororg/"></script>
  </head>
</html>
```

This issue is just intended to let you know in case your monitoring did not already catch this. Feel free to close if this is a known issue.

**Comment by crazyideas21** [comment]
Hi @malexmave,

Did you turn off javascript in your browser? Could you submit a screenshot? I have no issue opening the page in major browsers:

![image](https://user-images.githubusercontent.com/1479070/81713284-a9295780-9443-11ea-93d0-e8185d7435e2.png)

Thanks!

Danny

**Comment by malexmave** [comment]
Looks like I found the culprit: 
![image](https://user-images.githubusercontent.com/1688580/81735084-d18d7200-9494-11ea-9bb0-31e8437e7d58.png)

Some necessary JavaScript seems to have ended up on a block list used by uBlock Origin. So, it doesn't seem like it is an issue with the IoTInspector website itself - closing this, but at least now you know the reason in case others report similar issues.

**Comment by crazyideas21** [comment]
Thanks for pointing out the issue, @malexmave!
