### ISSUE TITLE
Error downloading the latest IoT Inspector (Win10 install)

### ISSUE THREAD

**Issue by cathsaigh** [noise-lab/iot-inspector-client#90]
Followed directions and ran "update_inspector.bat".  Received following message:

Downloading the latest version of IoT Inspector...
Error downloading the latest IoT Inspector.
Press any key to exit.

Any ideas?

**Comment by crazyideas21** [comment]
We're down for maintenance today.

**Comment by crazyideas21** [comment]
We're done with maintenance. Try again.

**Comment by Bruce5901** [comment]
Batch file is returning the following:

Downloading the latest version of IoT Inspector...
Error downloading the latest IoT Inspector.
Press any key to exit.

Any Ideas of how to proceed?
